In [7]:
import pandas as pd

#读取员工数据
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/employees.csv")
df

#按department_id 分组。计算salary 的最小值，中位数，最大值
df.groupby("department_id")["salary"].agg(["min","median","max"])

                   min   median      max
department_id
10.0            4400.0   4400.0   4400.0
20.0            6000.0   9500.0  13000.0
30.0            2500.0   2850.0  11000.0
40.0            6500.0   6500.0   6500.0
50.0            2100.0   3100.0   8200.0
60.0            4200.0   4800.0   9000.0
70.0           10000.0  10000.0  10000.0
80.0            6100.0   8900.0  14000.0
90.0           17000.0  17000.0  24000.0
100.0           6900.0   8000.0  12000.0
110.0           8300.0  10150.0  12000.0

In [15]:
#针对不同的聚合字段进行不同的聚合操作
# 按department_id 分组，统计job_id 的种类数，commission_pct的平均值
df.groupby("department_id").agg({"job_id":"nunique","commission_pct":"mean"})

# df.groupby("department_id")[["job_id","commission_pct"]].agg(["nunique","max"])

df.groupby("department_id").agg({"job_id":"nunique","commission_pct":"mean"}).rename(columns={"job_id":"岗位数","commission_pct":"平均值"})

df.groupby("department_id").agg(岗位数=("job_id","nunique"),平均值=("commission_pct","mean"))

               岗位数    平均值
department_id
10.0             1    NaN
20.0             2    NaN
30.0             2    NaN
40.0             1    NaN
50.0             3    NaN
60.0             1    NaN
70.0             1    NaN
80.0             2  0.225
90.0             2    NaN
100.0            2    NaN
110.0            2    NaN

In [17]:
#自定义聚合函数操作
#统计每个部门员工lastname 首字母
def f(x):
    result = set()
    for i in x:
        result.add(i[0])
    return result

df.groupby("department_id")["last_name"].agg(f)

department_id
10.0                                                   {W}
20.0                                                {F, H}
30.0                                    {B, T, C, K, R, H}
40.0                                                   {M}
50.0     {C, N, E, W, B, K, A, J, L, V, M, S, T, D, O, ...
60.0                                       {E, A, P, H, L}
70.0                                                   {B}
80.0     {C, E, Z, B, K, A, J, L, M, V, S, T, D, P, O, ...
90.0                                                {D, K}
100.0                                   {S, U, C, F, P, G}
110.0                                               {G, H}
Name: last_name, dtype: object

### transform分组转换

In [20]:
import pandas as pd

#读取员工数据
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/employees.csv")
df

df.groupby("department_id")["salary"].transform(lambda x:x - x.mean())

0      4666.666667
1     -2333.333333
2     -2333.333333
3      3240.000000
4       240.000000
          ...
102   -3500.000000
103       0.000000
104       0.000000
105    1850.000000
106   -1850.000000
Name: salary, Length: 107, dtype: float64

In [31]:
#2）通过transform()按分组使用平均值填充缺失值
import pandas as pd
import numpy as np
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/employees.csv")
df

na_index = pd.Series(df.index.tolist()).sample(30)
na_index

df.loc[na_index, "salary"] = pd.NA
print(df.groupby("department_id")["salary"].agg(["size","count"])) #查看每组数据总数与非空数据数

def fill_missing(x):
    #使用平均值填充
    if np.isnan(x.mean()):
        return x.fillna(0)
    return x.fillna(x.mean())
df["salary"] = df.groupby("department_id")["salary"].transform(fill_missing)
print(df.groupby("department_id")["salary"].agg(["size","count"]))

               size  count
department_id
10.0              1      0
20.0              2      1
30.0              6      4
40.0              1      0
50.0             45     32
60.0              5      4
70.0              1      1
80.0             34     27
90.0              3      1
100.0             6      4
110.0             2      2
               size  count
department_id
10.0              1      1
20.0              2      2
30.0              6      6
40.0              1      1
50.0             45     45
60.0              5      5
70.0              1      1
80.0             34     34
90.0              3      3
100.0             6      6
110.0             2      2

In [33]:
#分组过滤

commission_pct_filter = df.groupby("department_id").filter(
  lambda x: x["commission_pct"].notnull().all()
) # 按department_id分组，过滤掉commission_pct包含空值的分组
print(commission_pct_filter)

    employee_id   first_name   last_name     email        phone_number  \
45          145         John     Russell   JRUSSEL  011.44.1344.429268
46          146        Karen    Partners  KPARTNER  011.44.1344.467268
47          147      Alberto   Errazuriz  AERRAZUR  011.44.1344.429278
48          148       Gerald   Cambrault  GCAMBRAU  011.44.1344.619268
49          149        Eleni     Zlotkey  EZLOTKEY  011.44.1344.429018
50          150        Peter      Tucker   PTUCKER  011.44.1344.129268
51          151        David   Bernstein  DBERNSTE  011.44.1344.345268
52          152        Peter        Hall     PHALL  011.44.1344.478968
53          153  Christopher       Olsen    COLSEN  011.44.1344.498718
54          154      Nanette   Cambrault  NCAMBRAU  011.44.1344.987668
55          155       Oliver     Tuvault  OTUVAULT  011.44.1344.486508
56          156      Janette        King     JKING  011.44.1345.429268
57          157      Patrick       Sully    PSULLY  011.44.1345.929268
58          158        Allan      McEwen   AMCEWEN  011.44.1345.829268
59          159      Lindsey       Smith    LSMITH  011.44.1345.729268
60          160       Louise       Doran    LDORAN  011.44.1345.629268
61          161       Sarath      Sewall   SSEWALL  011.44.1345.529268
62          162        Clara     Vishney  CVISHNEY  011.44.1346.129268
63          163     Danielle      Greene   DGREENE  011.44.1346.229268
64          164       Mattea     Marvins  MMARVINS  011.44.1346.329268
65          165        David         Lee      DLEE  011.44.1346.529268
66          166       Sundar        Ande     SANDE  011.44.1346.629268
67          167         Amit       Banda    ABANDA  011.44.1346.729268
68          168         Lisa        Ozer     LOZER  011.44.1343.929268
69          169     Harrison       Bloom    HBLOOM  011.44.1343.829268
70          170       Tayler         Fox      TFOX  011.44.1343.729268
71          171      William       Smith    WSMITH  011.44.1343.629268
72          172    Elizabeth       Bates    EBATES  011.44.1343.529268
73          173      Sundita       Kumar    SKUMAR  011.44.1343.329268
74          174        Ellen        Abel     EABEL  011.44.1644.429267
75          175       Alyssa      Hutton   AHUTTON  011.44.1644.429266
76          176     Jonathon      Taylor   JTAYLOR  011.44.1644.429265
77          177         Jack  Livingston  JLIVINGS  011.44.1644.429264
79          179      Charles     Johnson  CJOHNSON  011.44.1644.429262

    job_id       salary  commission_pct  manager_id  department_id
45  SA_MAN  14000.00000            0.40       100.0           80.0
46  SA_MAN  13500.00000            0.30       100.0           80.0
47  SA_MAN  12000.00000            0.30       100.0           80.0
48  SA_MAN  11000.00000            0.30       100.0           80.0
49  SA_MAN  10500.00000            0.20       100.0           80.0
50  SA_REP  10000.00000            0.30       145.0           80.0
51  SA_REP   9500.00000            0.25       145.0           80.0
52  SA_REP   9000.00000            0.25       145.0           80.0
53  SA_REP   9029.62963            0.20       145.0           80.0
54  SA_REP   7500.00000            0.20       145.0           80.0
55  SA_REP   9029.62963            0.15       145.0           80.0
56  SA_REP  10000.00000            0.35       146.0           80.0
57  SA_REP   9500.00000            0.35       146.0           80.0
58  SA_REP   9029.62963            0.35       146.0           80.0
59  SA_REP   8000.00000            0.30       146.0           80.0
60  SA_REP   9029.62963            0.30       146.0           80.0
61  SA_REP   7000.00000            0.25       146.0           80.0
62  SA_REP  10500.00000            0.25       147.0           80.0
63  SA_REP   9500.00000            0.15       147.0           80.0
64  SA_REP   7200.00000            0.10       147.0           80.0
65  SA_REP   6800.00000            0.10       147.0           80.0
66  SA_REP   6400.00000            0.10       147.0           80.0
67  SA_REP   6200.00000            0.10       147.0           80.0
68  SA_REP  11500.00000            0.25       148.0           80.0
69  SA_REP  10000.00000            0.20       148.0           80.0
70  SA_REP   9029.62963            0.20       148.0           80.0
71  SA_REP   7400.00000            0.15       148.0           80.0
72  SA_REP   7300.00000            0.15       148.0           80.0
73  SA_REP   6100.00000            0.10       148.0           80.0
74  SA_REP   9029.62963            0.30       149.0           80.0
75  SA_REP   8800.00000            0.25       149.0           80.0
76  SA_REP   9029.62963            0.20       149.0           80.0
77  SA_REP   8400.00000            0.20       149.0           80.0
79  SA_REP   6200.00000            0.10       149.0           80.0