In [42]:
import pandas as pd
from datetime import datetime
date2 = datetime.now()
type(date2)

#几种时间类型
# datetime
# Timestamp
# datetime64
# DatetimeIndex
# period
# PeriodIndex


t = pd.to_datetime("2026-01-18")
t

df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/weather.csv")
df["ymd"] = pd.to_datetime(df["date"])
# df.info()
# df.set_index("ymd",inplace=True)
df["month"] = df["ymd"].dt.to_period("M")
df.set_index("month", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
PeriodIndex: 1461 entries, 2012-01 to 2015-12
Freq: M
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   object
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
 6   ymd            1461 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(2)
memory usage: 91.3+ KB

# Python中的日期与时间工具datetime

In [43]:
from datetime import datetime

date1 = datetime(year=2000, month=1, day=1)
date2 = datetime.now()
print(date1) # 2000-01-01 00:00:00
print(date2) # 2025-01-01 00:00:00
print(date1.year) # 2000
print(date1.month) # 1
print(date1.day) # 1
print(date2.weekday()) # 5
print(date2.strftime("%A")) # Saturday
print(date2 - date1) # 18263 days, 0:00:00

2000-01-01 00:00:00
2026-10-16 15:44:09.717433
2000
1
1
4
Friday
9785 days, 15:44:09.717433

In [45]:
#在加载数据的时候，通过parse_dates 将日期字符串直接转换为TimeStamp类型
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/weather.csv",parse_dates=["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   datetime64[ns]
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 68.6+ KB

In [47]:
#提取timestamp的各个部分
d = pd.Timestamp("2015-01-01 09:08:07.123456")
print(d.year) # 2015
print(d.month) # 1
print(d.day) # 1
print(d.hour) # 9
print(d.minute) # 8
print(d.second) # 7
print(d.microsecond) # 123456

2015
1
1
9
8
7
123456

In [57]:
#Series通过时间属性访问器对象访问
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/weather.csv")
df_date = pd.to_datetime(df["date"])
df_date

df["year"] = df_date.dt.year
df["month"] = df_date.dt.month
df["day"] = df_date.dt.day
# df.info()

df["quarter"] = pd.to_datetime(df["date"]).dt.to_period("Q") # 将 年-月-日 转换为 年季度
# print(df[["date", "quarter"]].head())
df.set_index("quarter", inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
PeriodIndex: 1461 entries, 2012Q1 to 2015Q4
Freq: Q-DEC
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   object
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
 6   year           1461 non-null   int32
 7   month          1461 non-null   int32
 8   day            1461 non-null   int32
dtypes: float64(4), int32(3), object(2)
memory usage: 97.0+ KB

# timedelta64

In [60]:
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/weather.csv")
df_date = pd.to_datetime(df["date"])
timedelta = df_date - df_date[0]
timedelta

df["day_diff"] = timedelta
df.set_index("day_diff", inplace=True)
df.info() #TimedeltaIndex

<class 'pandas.core.frame.DataFrame'>
TimedeltaIndex: 1461 entries, 0 days to 1460 days
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1461 non-null   object
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object
dtypes: float64(4), object(2)
memory usage: 79.9+ KB

# 时间索引

In [67]:
df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/weather.csv")
df
df["date"] = pd.to_datetime(df["date"]) # 将date列转换为datetime64类型
df.set_index("date", inplace=True) # 将date列设置为索引
# df.info()

df.loc["2013-01":"2013-06"]
print(df.loc["2015"]) # 获取2015年所有数据
#通过between_time()和at_time()获取某些时刻的数据
df.between_time("9:00", "11:00") # 获取9:00到11:00之间的数据
df.at_time("3:33") # 获取3:33的数据

            precipitation  temp_max  temp_min  wind weather
date
2015-01-01            0.0       5.6      -3.2   1.2     sun
2015-01-02            1.5       5.6       0.0   2.3    rain
2015-01-03            0.0       5.0       1.7   1.7     fog
2015-01-04           10.2      10.6       3.3   4.5    rain
2015-01-05            8.1      12.2       9.4   6.4    rain
...                   ...       ...       ...   ...     ...
2015-12-27            8.6       4.4       1.7   2.9    rain
2015-12-28            1.5       5.0       1.7   1.3    rain
2015-12-29            0.0       7.2       0.6   2.6     fog
2015-12-30            0.0       5.6      -1.0   3.4     sun
2015-12-31            0.0       5.6      -2.1   3.5     sun

[365 rows x 5 columns]

Empty DataFrame
Columns: [precipitation, temp_max, temp_min, wind, weather]
Index: []

# 生成时间序列

In [69]:
pd.date_range("2015-07-03", "2015-07-10")

pd.date_range("2015-07-03", periods=5)

pd.date_range("2015-07-03", periods=5, freq="h")

pd.date_range("2015-07-03", periods=10, freq="QE-FEB")

pd.date_range("2015-07-03", periods=10, freq="2h30min")

df = pd.read_csv(r"/Users/blucechen/PycharmProjects/pythontest/data/weather.csv")
# 重新采样 其实就是分组
df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)
df

df[["temp_max", "temp_min"]].resample("YE").mean()

             temp_max  temp_min
date
2012-12-31  15.276776  7.289617
2013-12-31  16.058904  8.153973
2014-12-31  16.995890  8.662466
2015-12-31  17.427945  8.835616